create table if not exists brigades
(
    id             INT generated by default as identity primary key,
    salary         DOUBLE PRECISION NOT NULL,
    brigade_status VARCHAR          NOT NULL

);

create table if not exists brigades_employees
(
    brigade_id  INT NOT NULL,
    employee_id INT NOT NULL
);

create table if not exists construct_objects
(
    id     INT generated by default as identity primary key,
    square DOUBLE PRECISION NOT NULL,
    type   VARCHAR          NOT NULL
);

create table if not exists employees
(
    id            INT generated by default as identity primary key,
    password      VARCHAR NOT NULL,
    first_name    VARCHAR NOT NULL,
    last_name     VARCHAR NOT NULL,
    phone_number  VARCHAR NOT NULL UNIQUE,
    email         VARCHAR NOT NULL UNIQUE,
    speciality    VARCHAR NOT NULL,
    employee_role VARCHAR NOT NULL
);

create table if not exists orders
(
    id                  INT generated by default as identity primary key,
    address             VARCHAR NOT NULL,
    beginning_of_work   DATE    NOT NULL,
    end_of_work         DATE    NOT NULL,
    brigade_id          INT     ,
    user_id             INT     NOT NULL,
    order_status        VARCHAR NOT NULL,
    construct_object_id INT     NOT NULL
);

create table if not exists orders_stocks
(
    order_id INT NOT NULL,
    stock_id INT NOT NULL,
    count    INT NOT NULL
);

create table if not exists stock
(
    id                 INT generated by default as identity primary key,
    name               VARCHAR NOT NULL,
    unit_price         INT     NOT NULL,
    count_of_materials INT     NOT NULL,
    purchase_date      DATE    NOT NULL,
    supplier_id        INT     NOT NULL
);

create table if not exists suppliers
(
    id     INT generated by default as identity primary key,
    name   varchar          NOT NULL,
    rating DOUBLE PRECISION not null
);

create table if not exists users
(
    id           INT Generated by default as identity primary key,
    password     VARCHAR NOT NULL,
    first_name   VARCHAR NOT NULL,
    last_name    VARCHAR NOT NULL,
    phone_number VARCHAR NOT NULL UNIQUE,
    email        VARCHAR NOT NULL UNIQUE,
    discount     integer not null
);


alter table if exists brigades_employees
    add constraint brigade_employees_employees_id_fk foreign key (employee_id) references employees (id);

alter table if exists brigades_employees
    add constraint brigade_employees_brigade_id_fk foreign key (brigade_id) references brigades (id);

alter table if exists orders
    add constraint orders_brigades_id_fk foreign key (brigade_id) references brigades (id);

alter table if exists orders
    add constraint orders_construct_objects_id_fk foreign key (construct_object_id) references construct_objects (id);

alter table if exists orders
    add constraint orders_users_id_fk foreign key (user_id) references users (id);

alter table if exists orders_stocks
    add constraint orders_stocks_stock_id_fk foreign key (stock_id) references stock (id);

alter table if exists orders_stocks
    add constraint orders_stocks_orders_id_fk foreign key (order_id) references orders (id);

alter table if exists stock
    add constraint stock_suppliers_id_fk foreign key (supplier_id) references suppliers (id);


insert into users (password, first_name, last_name, phone_number, email, discount)
values ('sasha123', 'Alex', 'Popel', '+375336405535', 'alex@gmail.com', 12);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('hohmas', 'Petya', 'Pop', '+375338172121', 'petya@gmail.com', 11);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('poaien', 'Paulo', 'Horp', '+375334171212', 'paulo@gmail.com', 2);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('4124das', 'Igor', 'Jori', '+375339301039', 'igor@gmail.com', 3);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('fqwgw12', 'Kirill', 'Ivanov', '+375292352323', 'kirill@gmail.com', 31);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('112jxz1', 'Yulia', 'Velikaya', '+375290190101', 'yulia@gmail.com', 100);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('kfpjh12', 'Tanya', 'Venskovich', '+375292820202', 'tanya@gmail.com', 9);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('ogjonao123', 'Anya', 'Zdanevich', '+375339282828', 'anya@gmail.com', 4);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('kakdnl1245', 'Polina', 'Kucha', '+375337483434', 'polina@gmail.com', 3);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('lfqfml1', 'Alexander', 'Ivashko', '+375336401245', 'popapan@gmail.com', 2);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('nastya123', 'Nastya', 'Vashenok', '+375331516262', 'nastya@gmail.com', 64);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('lgskgj1251', 'Sanya', 'Falafel', '+375333801020', 'sanyaa@gmail.com', 14);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('kaj3bml1n2', 'Nastya', 'Zhigadlo', '+375339439949', 'pulia@gmail.com', 51);

insert into users (password, first_name, last_name, phone_number, email, discount)
values ('pagnkqlk12', 'Pavel', 'Khanko', '+375293892929', 'pashaa12@gmail.com', 51);
insert into users ( password, first_name, last_name, phone_number, email, discount)
values ('lasjhf1251', 'Zhorik', 'Kvart', '+375293829229', 'grusha@gmail.com', 52);


insert into suppliers ( name, rating)
values ('GlobalGreen', 5);
insert into suppliers (name, rating)
values ('GlobalRed', 2);
insert into suppliers ( name, rating)
values ('GlobalBlue', 3);
insert into suppliers (name, rating)
values ('Reforged', 5);
insert into suppliers (name, rating)
values ('Jollibbu', 1);
insert into suppliers (name, rating)
values ('ProstoKva', 5);
insert into suppliers (name, rating)
values ('ZheloZubali', 4);
insert into suppliers (name, rating)
values ('KoronaTrue', 3);
insert into suppliers (name, rating)
values ('PotolkiHa', 1);
insert into suppliers (name, rating)
values ('StroyTrest', 2);



insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('hoho', 'Zhorik', 'Konev', '+375332323323', 'zhor@gmail.com', 'builder', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('klafklh124', 'Paulos', 'Kuharev', '+375332512512', 'paulos@gmail.com', 'engineer', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('1', 'Alexander', 'Ivashko', '+375338181414', 'admin@gmail.com', 'manager', 'DIRECTOR');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('akldnp12', 'Kristina', 'Papa', '+375334124242', 'krist@gmail.com', 'manager', 'DIRECTOR');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('alnblsl124', 'Goga', 'Guda', '+375339249242', 'goga@gmail.com', 'manager', 'DIRECTOR');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('asnansg', 'Horny', 'Frenk', '+375330921232', 'horny@gmail.com', 'engineer', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('lgdnbo21', 'Padro', 'Sviat', '+375331111111', 'padro@gmail.com', 'builder', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('sqgqlnl12', 'Kukla', 'Vudu', '+375338554141', 'kukla@gmail.com', 'electrician', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('lllasnlglase', 'Venya', 'Galavach', '+375295151515', 'galavach@gmail.com', 'engineer', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('kvanaska', 'Poka', 'Guda', '+375337241451', 'poka41@gmail.com', 'engineer', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('lkanskl24', 'Zhenya', 'Pinoke', '+375338518252', 'pinok124@gmail.com', 'builder', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('lgmalsmgl24', 'Vasya', 'Ivashko', '+37533852823', 'vasya41@gmail.com', 'electrician', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('asgnknwqo51', 'Grisha', 'Galavach', '+375296512225', 'grish@gmail.com', 'engineer', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('askfnoqw41', 'Grigoriy', 'Lavrov', '+3753385710101', 'grigga@gmail.com', 'builder', 'WORKER');

insert into employees (password, first_name, last_name, phone_number, email, speciality, employee_role)
values ('241gasgqwq', 'Vasya', 'Galavach', '+375337777777', 'loej@gmail.com', 'electrician', 'WORKER');

insert into construct_objects (square, type)
values (1241, 'PARKING');
insert into construct_objects (square, type)
values (523, 'COTTAGE');
insert into construct_objects (square, type)
values (251, 'HIGH_RISES');
insert into construct_objects (square, type)
values (1321, 'PARKING');
insert into construct_objects (square, type)
values (421, 'COTTAGE');
insert into construct_objects (square, type)
values (246, 'HIGH_RISES');
insert into construct_objects (square, type)
values (2512, 'PARKING');
insert into construct_objects (square, type)
values (211, 'COTTAGE');
insert into construct_objects (square, type)
values (372, 'HIGH_RISES');
insert into construct_objects (square, type)
values (6132, 'PARKING');
insert into construct_objects (square, type)
values (273, 'COTTAGE');
insert into construct_objects (square, type)
values (723, 'HIGH_RISES');
insert into construct_objects (square, type)
values (1241, 'PARKING');
insert into construct_objects (square, type)
values (235, 'COTTAGE');
insert into construct_objects (square, type)
values (632, 'HIGH_RISES');
insert into construct_objects (square, type)
values (1326, 'PARKING');
insert into construct_objects (square, type)
values (274, 'COTTAGE');
insert into construct_objects (square, type)
values (322, 'HIGH_RISES');
insert into construct_objects (square, type)
values (2362, 'PARKING');
insert into construct_objects (square, type)
values (432, 'COTTAGE');
insert into construct_objects (square, type)
values (263, 'HIGH_RISES');
insert into construct_objects (square, type)
values (2141, 'PARKING');
insert into construct_objects (square, type)
values (823, 'COTTAGE');
insert into construct_objects (square, type)
values (342, 'HIGH_RISES');

insert into brigades (salary, brigade_status)
values (8210, 'USED');
insert into brigades (salary, brigade_status)
values (8510, 'USED');
insert into brigades (salary, brigade_status)
values (5373, 'USED');
insert into brigades (salary, brigade_status)
values (3834, 'FREE');
insert into brigades (salary, brigade_status)
values (9365, 'FREE');
insert into brigades (salary, brigade_status)
values (8544, 'FREE');



insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.napoleona', '2020-01-20', '2020-04-30', 1, 1, 'COMPLETED', 1);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.vertuhova', '2020-01-13', '2020-03-21', 2, 2, 'COMPLETED', 2);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.veselova', '2020-01-01', '2020-12-31', 3, 3, 'COMPLETED', 3);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.kruzha', '2022-01-01', '2022-08-24', 1, 5, 'IN_PROGRESS', 5);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.krasnaya', '2022-01-20', '2022-05-10', 1, 4, 'COMPLETED', 6);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.zelenaya', '2022-01-13', '2022-06-23', 1, 6, 'IN_PROGRESS', 8);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.polnaya', '2022-05-12', '2022-10-14', 3, 7, 'IN_PROGRESS', 9);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.rozambaun', '2022-06-29', '2022-12-15', 2, 8, 'FORMED', 10);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.bolshaya', '2022-08-20', '2023-04-12', 3, 9, 'FORMED', 13);
insert into orders (address, beginning_of_work, end_of_work, brigade_id, user_id, order_status, construct_object_id)
values ('ul.grustnaya', '2023-01-20', '2023-06-14', 5, 10, 'FORMED', 15);

insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('desk', '12', 1000, '2020-12-01', 1);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('metal', '42', 1241, '2020-06-21', 2);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('tile', '60', 4000, '2020-07-01', 3);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('wood', '26', 521, '2020-03-21', 4);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('concrete', '15', 2000, '2021-01-01', 5);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('beams', '50', 201, '2021-04-01', 6);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('window', '40', 102, '2021-05-01', 7);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('plinth', '4', 251, '2021-07-01', 8);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('linoleum', '16', 263, '2021-03-01', 9);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('metal', '31', 1000, '2021-12-01', 10);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('door', '71', 523, '2022-01-01', 1);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('shingles', '2', 10200, '2022-02-01', 2);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('openin', '5', 512, '2022-04-01', 3);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('wire', '3', 5000, '2022-03-01', 4);
insert into stock (name, unit_price, count_of_materials, purchase_date, supplier_id)
values ('bulb', '4', 4000, '2022-05-01', 5);

insert into orders_stocks (order_id, stock_id, count)
values (1, 1, 100);
insert into orders_stocks (order_id, stock_id, count)
values (1, 2, 42);
insert into orders_stocks (order_id, stock_id, count)
values (1, 3, 51);
insert into orders_stocks (order_id, stock_id, count)
values (2, 1, 21);
insert into orders_stocks (order_id, stock_id, count)
values (2, 1, 51);
insert into orders_stocks (order_id, stock_id, count)
values (3, 3, 21);
insert into orders_stocks (order_id, stock_id, count)
values (4, 7, 62);
insert into orders_stocks (order_id, stock_id, count)
values (5, 1, 73);
insert into orders_stocks (order_id, stock_id, count)
values (6, 3, 53);
insert into orders_stocks (order_id, stock_id, count)
values (7, 1, 53);
insert into orders_stocks (order_id, stock_id, count)
values (8, 6, 32);
insert into orders_stocks (order_id, stock_id, count)
values (9, 8, 52);
insert into orders_stocks (order_id, stock_id, count)
values (10, 2, 24);
insert into orders_stocks (order_id, stock_id, count)
values (1, 5, 51);
insert into orders_stocks (order_id, stock_id, count)
values (2, 12, 63);
insert into orders_stocks (order_id, stock_id, count)
values (3, 1, 24);
insert into orders_stocks (order_id, stock_id, count)
values (6, 14, 51);
insert into orders_stocks (order_id, stock_id, count)
values (5, 12, 23);
insert into orders_stocks (order_id, stock_id, count)
values (6, 15, 82);
insert into orders_stocks (order_id, stock_id, count)
values (3, 13, 42);
insert into orders_stocks (order_id, stock_id, count)
values (7, 5, 32);
insert into orders_stocks (order_id, stock_id, count)
values (8, 7, 25);
insert into orders_stocks (order_id, stock_id, count)
values (4, 8, 51);
insert into orders_stocks (order_id, stock_id, count)
values (7, 5, 83);
insert into orders_stocks (order_id, stock_id, count)
values (3, 4, 41);
insert into orders_stocks (order_id, stock_id, count)
values (1, 2, 12);
insert into orders_stocks (order_id, stock_id, count)
values (7, 6, 41);
insert into orders_stocks (order_id, stock_id, count)
values (2, 8, 42);

insert into brigades_employees(brigade_id, employee_id)
values (1, 1);
insert into brigades_employees(brigade_id, employee_id)
values (1, 2);
insert into brigades_employees(brigade_id, employee_id)
values (2, 3);
insert into brigades_employees(brigade_id, employee_id)
values (2, 4);
insert into brigades_employees(brigade_id, employee_id)
values (3, 5);
insert into brigades_employees(brigade_id, employee_id)
values (3, 6);
insert into brigades_employees(brigade_id, employee_id)
values (4, 7);
insert into brigades_employees(brigade_id, employee_id)
values (5, 8);
insert into brigades_employees(brigade_id, employee_id)
values (6, 9);
insert into brigades_employees(brigade_id, employee_id)
values (5, 10);
insert into brigades_employees(brigade_id, employee_id)
values (4, 11);







